version: '3'
services:
  db:
    image: postgres:latest
    container_name: db_postgres
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_DB: images_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi-image-processor:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
    environment:
      ENVIRONMENT: "docker"
      DATABASE_URL: "postgresql+asyncpg://exampleuser:examplepassword@db:5432/images_service"
      MINIO_URL: "minio:9000"
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "adminpassword"

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "adminpassword"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  minio_data:
