"""Delete file_path

Revision ID: 7faa9f8471e8
Revises: 46f40f021406
Create Date: 2025-01-07 00:51:40.850159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7faa9f8471e8'
down_revision: Union[str, None] = '46f40f021406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'images_metadata', ['id'])
    op.drop_column('images_metadata', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images_metadata', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'images_metadata', type_='unique')
    # ### end Alembic commands ###
